name: syncfusion_flutter_calendar
description: The Flutter Calendar widget has nine built-in configurable views that provide basic functionalities for scheduling and representing appointments/events efficiently.
version: 18.4.49
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  timezone: 0.6.1
  syncfusion_flutter_core: ^18.4.49
  syncfusion_flutter_datepicker: ^18.4.49-beta
  intl: ">=0.15.0 <0.20.0"

flutter:
  assets:
    - packages/timezone/data/2020a.tzf